/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.util.Calendar;

/**
 *
 * @author pi
 */
 
public class LeeCedula extends javax.swing.JFrame {
java.util.Calendar calendario; 
int dia, mes, año, hora, minutos, segundos; 
private javax.swing.JLabel label;  
    /**
     * Creates new form LeeCedula
     */
    public LeeCedula() {
        initComponents();
        reloj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JToggleButton();
        labelreloj = new javax.swing.JLabel();
        btnColacion = new javax.swing.JToggleButton();
        btnSalida = new javax.swing.JToggleButton();
        lbleventosel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrada.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnEntrada.setLabel("ENTRADA");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        labelreloj.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 80)); // NOI18N
        labelreloj.setText("Reloj");
        jPanel1.add(labelreloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        btnColacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnColacion.setLabel("COLACION");
        btnColacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnColacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        btnSalida.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSalida.setLabel("SALIDA");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        lbleventosel.setText("Evento");
        jPanel1.add(lbleventosel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 229, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        // TODO add your handling code here:
        btnColacion.setSelected(false);
        btnSalida.setSelected(false);

        lbleventosel.setText("0");
        //   jTextField1.requestFocus();
        try{
            conexion.getConexion();
        }catch(Exception e){

        }finally{
            conexion.cierra();
        }

    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnColacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColacionActionPerformed
        btnEntrada.setSelected(false);
        btnSalida.setSelected(false);
        lbleventosel.setText("5");
        jTextField1.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnColacionActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        btnEntrada.setSelected(false);
        btnColacion.setSelected(false);
        lbleventosel.setText("1");
        jTextField1.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed
  private void reloj() { 
calendario = new java.util.GregorianCalendar(); 
segundos = calendario.get(Calendar.SECOND); 
javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() { 
@ Override 
public void actionPerformed(java.awt.event.ActionEvent ae) { 
java.util.Date actual = new java.util.Date(); 
calendario.setTime(actual); 
dia = calendario.get(Calendar.DAY_OF_MONTH); 
mes = (calendario.get(Calendar.MONTH) + 1); 
año = calendario.get(Calendar.YEAR); 
hora = calendario.get(Calendar.HOUR_OF_DAY); 
minutos = calendario.get(Calendar.MINUTE); 
segundos = calendario.get(Calendar.SECOND); 
String hour ="" ;
String date = "";
 hour = String.format("%02d : %02d : %02d", hora, minutos, segundos); 
 date = String.format("%02d / %02d / %02d", dia, mes, año); 
labelreloj.setText("<html><center>" + hour + "<br><h1>" + date+"</h1>"); 
   } 
}); 
timer.start(); 
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeeCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeeCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeeCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeeCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeeCedula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnColacion;
    private javax.swing.JToggleButton btnEntrada;
    private javax.swing.JToggleButton btnSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelreloj;
    private javax.swing.JLabel lbleventosel;
    // End of variables declaration//GEN-END:variables
}
